### ISSUE TITLE
401 error when I trying to run integration with .env file

### ISSUE THREAD

**Issue by pprathameshmore** [JupiterOne/graph-jira#80]
I was trying to run this integration using local env variables

![image](https://user-images.githubusercontent.com/17108186/105347753-58424380-5c0d-11eb-8a6f-ca1073d5061a.png)

Might API deprecated

https://confluence.atlassian.com/cloud/deprecation-of-basic-authentication-with-passwords-for-jira-and-confluence-apis-972355348.html

@aiwilliams Thanks

**Comment by aiwilliams** [comment]
Thanks for creating this issue @pprathameshmore, sorry for the delayed response!

Please check out https://github.com/JupiterOne/graph-jira/blob/master/docs/jupiterone-io/graph-jira.md for the latest instructions. We guide users to use an API token instead of basic auth.
